# Generated by Django 4.1.2 on 2022-11-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsStories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="body_text",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="story",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
