# Generated by Django 4.1.2 on 2022-11-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsStories", "0002_alter_story_body_text_alter_story_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="body_text",
            field=models.CharField(max_length=1000),
        ),
    ]
