# Generated by Django 4.1.2 on 2022-11-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newsStories", "0005_alter_story_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="pub_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="story",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="newsStories.source",
            ),
        ),
    ]
